### ISSUE TITLE
HTML indentation

### ISSUE THREAD

**Issue by SidTheEngineer** [sjbcodes/prj-rev-bwfs-dasmoto#1]
Right now, the indentation throughout the `index.html` is just _slightly_ off. Remember that the only time we need to indent is when we have elements contained within other elements. 

**Example:**

Need to indent here:
```HTML
<div class="outer-container">
  <div class="inner-container">
    <h1>Some example text</h1>
  </div>
</div>
```

No need to indent here
```HTML
<h1>Some example text</h1>
<h2>More example text</h2>
<p>Example paragraph ... </p>
<img src="example.com" />
```

This is correctly done for the `<body>` tag, however there are a couple of instances where we indent without needing to do so. See if you can hunt this down and make adjustments.

**Comment by sjbcodes** [comment]
Thanks Sid, I've made the adjustments and will keep this in mind going forward
