### ISSUE TITLE
Notes on CSS

### ISSUE THREAD

**Issue by SidTheEngineer** [sjbcodes/prj-rev-bwfs-dasmoto#2]
Overall, your `style.css` file looks good 👍. There aren't any issues with formatting or syntax for the most part. One small adjustment I would suggest making here is to ensure that the path you're providing for the background image of the header is correct so the image shows up on the site. Remember that when can use `./` or `../` in front of the path to refer to the current directory or one level up, respectively.

**Comment by sjbcodes** [comment]
Oops, I did this for the images in the index.html file but messed up that one, thanks for pointing it out
